// -*- C++ -*- generated by wxGlade 0.4.1 on Sun May 28 11:06:01 2006

#include "GotoDlgPanel.h"


GotoDlgPanel::GotoDlgPanel(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: GotoDlgPanel::GotoDlgPanel
    label_1 = new wxStaticText(this, IDC_ADDR_LBL, wxT("&Address"));
    const wxString cbAddress_choices[] = {
        
    };
    cbAddress = new wxComboBox(this, IDC_ADDRESS, wxT(""), wxDefaultPosition, wxDefaultSize, 0, cbAddress_choices, wxCB_DROPDOWN);
    label_2 = new wxStaticText(this, -1, wxT("Prefix with \"+\", \"-\", or \"x\""));
    btnGetCursor = new wxButton(this, IDC_GET_CURSOR, wxT("Get &Cursor Position"));
    chkExtendSel = new wxCheckBox(this, -1, wxT("E&xtend Selection"));
    const wxString rbOrigin_choices[] = {
        wxT("&Absolute address"),
        wxT("&Beginning of file"),
        wxT("Cursor (&forward)"),
        wxT("Cursor (bac&kward)"),
        wxT("&End of file")
    };
    rbOrigin = new wxRadioBox(this, -1, wxT("&Origin"), wxDefaultPosition, wxDefaultSize, 5, rbOrigin_choices, 0, wxRA_SPECIFY_ROWS);
    btnGo = new wxButton(this, wxID_OK, wxT("&Go"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(GotoDlgPanel, wxPanel)
    // begin wxGlade: GotoDlgPanel::event_table
    EVT_TEXT(IDC_ADDRESS, GotoDlgPanel::OnAddressChange)
    EVT_BUTTON(IDC_GET_CURSOR, GotoDlgPanel::OnGetCursor)
    EVT_BUTTON(wxID_OK, GotoDlgPanel::OnGo)
    // end wxGlade
END_EVENT_TABLE();


void GotoDlgPanel::OnAddressChange(wxCommandEvent &event)
{
    event.Skip();
}


void GotoDlgPanel::OnGetCursor(wxCommandEvent &event)
{
    event.Skip();
}


void GotoDlgPanel::OnGo(wxCommandEvent &event)
{
    event.Skip();
}


// wxGlade: add GotoDlgPanel event handlers


void GotoDlgPanel::set_properties()
{
    // begin wxGlade: GotoDlgPanel::set_properties
    rbOrigin->SetSelection(0);
    // end wxGlade
}


void GotoDlgPanel::do_layout()
{
    // begin wxGlade: GotoDlgPanel::do_layout
    wxBoxSizer* topSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* hSizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* vSizer = new wxBoxSizer(wxVERTICAL);
    vSizer->Add(label_1, 0, wxADJUST_MINSIZE, 10);
    vSizer->Add(cbAddress, 0, wxTOP|wxBOTTOM|wxEXPAND|wxADJUST_MINSIZE, 10);
    vSizer->Add(label_2, 0, wxADJUST_MINSIZE, 0);
    vSizer->Add(btnGetCursor, 0, wxTOP|wxBOTTOM|wxADJUST_MINSIZE, 10);
    vSizer->Add(chkExtendSel, 0, wxADJUST_MINSIZE, 10);
    hSizer->Add(vSizer, 1, wxALL|wxEXPAND, 10);
    hSizer->Add(rbOrigin, 0, wxALL|wxADJUST_MINSIZE, 10);
    topSizer->Add(hSizer, 1, wxEXPAND, 0);
    topSizer->Add(btnGo, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 10);
    SetAutoLayout(true);
    SetSizer(topSizer);
    topSizer->Fit(this);
    topSizer->SetSizeHints(this);
    // end wxGlade
}

