// -*- C++ -*- generated by wxGlade 0.4.1 on Sun May 28 11:06:01 2006

#include <wx/wx.h>
#include <wx/image.h>

#ifndef GOTODLGPANEL_H
#define GOTODLGPANEL_H

// begin wxGlade: ::dependencies
// end wxGlade


class GotoDlgPanel: public wxPanel {
public:
    // begin wxGlade: GotoDlgPanel::ids
    // end wxGlade

    GotoDlgPanel(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: GotoDlgPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: GotoDlgPanel::attributes
    wxStaticText* label_1;
    wxComboBox* cbAddress;
    wxStaticText* label_2;
    wxButton* btnGetCursor;
    wxCheckBox* chkExtendSel;
    wxRadioBox* rbOrigin;
    wxButton* btnGo;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnAddressChange(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnGetCursor(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnGo(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // GOTODLGPANEL_H
