// -*- C++ -*- generated by wxGlade 0.4.1 on Sun May 28 10:49:42 2006

#include "GotoDialog.h"


GotoDialog::GotoDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: GotoDialog::GotoDialog
    label_1 = new wxStaticText(this, IDC_ADDR_LBL, wxT("&Address"));
    const wxString cbAddress_choices[] = {
        
    };
    cbAddress = new wxComboBox(this, IDC_ADDRESS, wxT(""), wxDefaultPosition, wxDefaultSize, 0, cbAddress_choices, wxCB_DROPDOWN);
    label_2 = new wxStaticText(this, -1, wxT("Prefix with \"+\", \"-\", or \"x\""));
    btnGetCursor = new wxButton(this, IDC_GET_CURSOR, wxT("Get &Cursor Position"));
    chkExtendSel = new wxCheckBox(this, -1, wxT("E&xtend Selection"));
    const wxString rbOrigin_choices[] = {
        wxT("&Beginning of file"),
        wxT("Cursor (&forward)"),
        wxT("Cursor (bac&kward)"),
        wxT("&End of file")
    };
    rbOrigin = new wxRadioBox(this, -1, wxT("&Origin"), wxDefaultPosition, wxDefaultSize, 4, rbOrigin_choices, 0, wxRA_SPECIFY_ROWS);
    btnGo = new wxButton(this, wxID_OK, wxT("&Go"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(GotoDialog, wxDialog)
    // begin wxGlade: GotoDialog::event_table
    EVT_TEXT(IDC_ADDRESS, GotoDialog::OnAddressChange)
    EVT_BUTTON(IDC_GET_CURSOR, GotoDialog::OnGetCursor)
    EVT_BUTTON(wxID_OK, GotoDialog::OnGo)
    // end wxGlade
END_EVENT_TABLE();


void GotoDialog::OnAddressChange(wxCommandEvent &event)
{
    event.Skip();
}


void GotoDialog::OnGetCursor(wxCommandEvent &event)
{
    event.Skip();
}


void GotoDialog::OnGo(wxCommandEvent &event)
{
    event.Skip();
}


// wxGlade: add GotoDialog event handlers


void GotoDialog::set_properties()
{
    // begin wxGlade: GotoDialog::set_properties
    SetTitle(wxT("Go To Address"));
    rbOrigin->SetSelection(0);
    // end wxGlade
}


void GotoDialog::do_layout()
{
    // begin wxGlade: GotoDialog::do_layout
    wxBoxSizer* topSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* hSizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* vSizer = new wxBoxSizer(wxVERTICAL);
    vSizer->Add(label_1, 0, wxADJUST_MINSIZE, 10);
    vSizer->Add(cbAddress, 0, wxTOP|wxBOTTOM|wxEXPAND|wxADJUST_MINSIZE, 10);
    vSizer->Add(label_2, 0, wxADJUST_MINSIZE, 0);
    vSizer->Add(btnGetCursor, 0, wxTOP|wxBOTTOM|wxADJUST_MINSIZE, 10);
    vSizer->Add(chkExtendSel, 0, wxADJUST_MINSIZE, 10);
    hSizer->Add(vSizer, 1, wxALL|wxEXPAND, 10);
    hSizer->Add(rbOrigin, 0, wxALL|wxADJUST_MINSIZE, 10);
    topSizer->Add(hSizer, 1, wxEXPAND, 0);
    topSizer->Add(btnGo, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 10);
    SetAutoLayout(true);
    SetSizer(topSizer);
    topSizer->Fit(this);
    topSizer->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}

